name: danielkbx
favicon: null
layout_spectrum: 0.8949616765603423
typography_spectrum: 0.7584022597875446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3526513259857893
  lightness: 0.10951817966997623
  saturation: 0.2171319725457579
  rhythmicContrast: 0.41514097317121923
purpose: []
